.DELETE_ON_ERROR:

makino_2010_ohnologs.xls:
	wget -O $@ 'https://www.pnas.org/action/downloadSupplement?doi=10.1073%2Fpnas.0914697107&file=st01.xls'

parampriya_2020_ohnologs_pairs_strict.tsv:
	wget -O $@ 'http://ohnologs.curie.fr/cgi-bin/DownloadBrowse.cgi?crit=[0]&org=hsapiens&opt=pairs&wgd=2R'
	#If not working try manually from Ohnologs V2 database: http://ohnologs.curie.fr/cgi-bin/BrowsePage.cgi?org=hsapiens
	#NR = 4,259
	
makino_2010_ohnologs.tsv: makino_2010_ohnologs.xls
	#Extract sheet 7 from Makino_2010_Ohnologs.xls  
	#NR = 9,062

parampriya_2020_ohnologs_pairs_strict_clean.tsv: parampriya_2020_ohnologs_pairs_strict.tsv
	awk -F"\t" 'NR>1 {print $$1 "\t" $$2}' $< > $@
	#Remove header row
	#NR = 4,258

makino_2010_ohnologs_clean.tsv: makino_2010_ohnologs.tsv
	awk -F"\t" 'NR>1 && $$1~/^ENSG/ {print $$1 "\t" $$4}' $< > $@
	#Remove header row and four comments rows
	#NR = 9,057 

ohnologs_makino_parampriya_merged.tsv: makino_2010_ohnologs_clean.tsv parampriya_2020_ohnologs_pairs_strict_clean.tsv 
	cat $^ | sort | uniq > $@
	#Merged databases and cleaned duplicates
	#NR = 11,800
	#(correctly slightly less than 4258+9057=13315)
	
ohnologs_makino_parampriya_merged.joint_id.tsv: ohnologs_makino_parampriya_merged.tsv
	awk -F"\t" '$$1<$$2 {print $$1":"$$2 "\t" "WGD"} $$1>=$$2{print $$2":"$$1 "\t" "WGD"}' $< | sort | uniq > $@
	#Dictionary to keep both SSD and WGD labeled in the same file containing all human paralogues
	####################################################################################################################
	##										!!!!!!!!!!OCCHIO PERCHÉ IL SORT | UNIQ MANCA NELLE ALTRE VERSIONI          									##
	####################################################################################################################

human_paralogs_biomart.tsv:
	wget -O $@ --post-file ../../local/src/mart_paralogs_query.xml 'http://www.ensembl.org/biomart/martservice'
	#Human genes from biomart with infos about paralogy
	#NR = 3,607,809
	
human_paralogs_biomart.halved.filtered.tsv: human_paralogs_biomart.tsv
	awk -F"\t" '$$1<$$3 && $$3!="" && ($$11=="within_species_paralog" || $$11=="other_paralog") {print $$0}' $< \
	| cut -f 1,3- > $@
	#Filtering and halving consists in picking paralogs and consider just A-B (since both A-B and B-A are present)
	#Second column is removed since it contains the gene_id with the Ensembl version (useless in our work)
	#"within_species_paralog" and "other_paralog" (see https://www.ensembl.org/info/website/glossary.html for the reason)
	#NR = 1,780,166
	
human_paralogs_biomart.halved.filtered.joint_id.tsv: human_paralogs_biomart.halved.filtered.tsv
	awk -F"\t" '{print $$0 "\t" $$1":"$$2 }' $< > $@
	#Add a columnt to append the label using the dictionary "ohnologs_makino_parampriya_merged.joint_id.tsv"
	
human_paralogs_biomart.halved.filtered.flagged.tsv: ohnologs_makino_parampriya_merged.joint_id.tsv human_paralogs_biomart.halved.filtered.joint_id.tsv
	translate -a -d -z -v -e SSD $< 14 < $(word 2, $^) | cut -f 1-13,15 > $@
	
commAncestors_list.tsv: human_paralogs_biomart.halved.filtered.tsv
	awk -F"\t" '{print $$9}' $< | sort | uniq > $@
	
commAncestors_list.labeled.tsv: comm_ancestors.tsv
	#Manual labelling with an ordinal number using https://www.ncbi.nlm.nih.gov/Taxonomy.
	#There's a file where this has been done manually in v1

gencode.v41.annotation.gtf.gz:
	wget -O $@ 'https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/gencode.v41.annotation.gtf.gz'
	
gencode.gtf.gz: gencode.v41.annotation.gtf.gz
	mv $< $@

gencode.gtf: gencode.gtf.gz
	gzip -d $<

gencode.geneOnly.gtf: gencode.gtf
	awk -F"\t" '$$3=="gene"' $< > $@
	#NR = 61,852
	
gencode.geneOnly.protcod.gtf: gencode.geneOnly.gtf
	awk -F"\t" '$$9~/gene_type "protein_coding"/' $< > $@
	#NR = 20,017
	
gencode.geneOnly.miRNA.gtf: gencode.geneOnly.gtf
	awk -F"\t" '$$9~/gene_type "miRNA"/' $< > $@
	#NR = 1,879

################################  gtf2bed conversion using gff2tab (super OP tool from ircc)  ################################################################
%.bed: %.gtf                                                                                                                                               
	cat $< | gff2tab gene_type gene_id gene_name | awk '{print $$1 "\t" $$4 "\t" $$5 "\t" substr($$10, 1, 15) "\t" $$6 "\t" $$7 "\t" $$9 "\t" $$11}' > $@
##############################################################################################################################################################

gencode.geneOnly.miRNA_intWithProtcod.bed: gencode.geneOnly.miRNA.bed gencode.geneOnly.protcod.bed
	bedtools intersect -a $< -b $(word 2, $^) > $@
	#NR = 1,278

gencode.geneOnly.miRNA_intWithGenes.bed: gencode.geneOnly.miRNA.bed gencode.geneOnly.bed
	bedtools intersect -a $< -b $(word 2, $^) > $@
	#NR = 3,845
		
protodictionary.protcod.tsv: gencode.geneOnly.miRNA_intWithProtcod.bed gencode.geneOnly.protcod.bed
	bedtools intersect -wb -a $< -b $(word 2, $^) > $@
	#NR = 1,444
	
protodictionary.genes.tsv: gencode.geneOnly.miRNA_intWithGenes.bed gencode.geneOnly.bed
	bedtools intersect -wb -a $< -b $(word 2, $^) > $@
	#NR = 8,639

dictionary.miRNA.tsv: protodictionary.tsv
	awk -F"\t" '{print $$12 "\t" $$15 "\t" $$16 "\t" $$4 "\t" $$7 "\t" $$8}' $< > $@
	#NR = 1,444

paralogs_miRNA_couples.tsv: human_paralogs_biomart.halved.filtered.flagged.tsv
	translate -a -d -v -e XXXXXX dictionary.tsv 1 2 < $< | grep -vw XXXXXX > $@



