.DELETE_ON_ERROR:

makino_2010_ohnologs.xls:
	wget -O $@ 'https://www.pnas.org/action/downloadSupplement?doi=10.1073%2Fpnas.0914697107&file=st01.xls'

parampriya_2020_ohnologs_pairs_strict.tsv:
	wget -O $@ 'http://ohnologs.curie.fr/cgi-bin/DownloadBrowse.cgi?crit=[0]&org=hsapiens&opt=pairs&wgd=2R'
	#If not working try manually from Ohnologs V2 database: http://ohnologs.curie.fr/cgi-bin/BrowsePage.cgi?org=hsapiens
	#NR = 4,259
	
makino_2010_ohnologs.tsv: makino_2010_ohnologs.xls
	#Extract sheet 7 from Makino_2010_Ohnologs.xls  
	#NR = 9,062

parampriya_2020_ohnologs_pairs_strict_clean.tsv: parampriya_2020_ohnologs_pairs_strict.tsv
	awk -F"\t" 'NR>1 {print $$1 "\t" $$2}' $< > $@
	#Remove header row
	#NR = 4,258

makino_2010_ohnologs_clean.tsv: makino_2010_ohnologs.tsv
	awk -F"\t" 'NR>1 && $$1~/^ENSG/ {print $$1 "\t" $$4}' $< > $@
	#Remove header row and four comments rows
	#NR = 9,057 

ohnologs_makino_parampriya_merged.tsv: makino_2010_ohnologs_clean.tsv parampriya_2020_ohnologs_pairs_strict_clean.tsv 
	cat $^ | sort | uniq > $@
	#Merged databases and cleaned duplicates
	#NR = 11,800
	#(correctly slightly less than 4258+9057=13315)

human_paralogs_biomart.tsv:
	wget -O $@ --post-file ../../local/src/mart_paralogs_query.xml 'http://www.ensembl.org/biomart/martservice'
	#Human genes from biomart with infos about paralogy
	#NR = 3,607,809
	
human_paralogs_biomart.halved.filtered.tsv: human_paralogs_biomart.tsv
	awk -F"\t" '$$1<$$3 && $$3!="" && $$11=="within_species_paralog" {print $$0}' $< \
	| cut -f 1,3- > $@
	#Filtering and halving consists in picking paralogs and consider just A-B (since both A-B and B-A are present)
	#Second column is removed since it contains the gene_id with the Ensembl version (useless in our work)
	#"within_species_paralog" because see https://www.ensembl.org/info/website/glossary.html
	#NR = 58,417
	
ohnologs_makino_parampriya_merged.filtered.tsv: ohnologs_makino_parampriya_merged.tsv human_paralogs_biomart.halved.filtered.tsv
	filter_2col 1 2 --both-orders $< < $(word 2, $^) > $@
	#Ohnologs confirmed as paralogs using Ensembl
	#In ohnologs_makino_parampriya_merged.tsv I have some redundand couples (noise)
	#this noise is cancelled since in human_paralogs_biomart.halved.filtered.tsv I have no redundancy
	#NR = 1,673 								(since the filter here allows 'within_species_paralog' only)

ssd_paralogs.tsv: ohnologs_makino_parampriya_merged.tsv human_paralogs_biomart.halved.filtered.tsv
	filter_2col 1 2 -v --both-orders $< < $(word 2, $^) > $@
	#NR _ 56,744

	
commAncestors_list.tsv: human_paralogs_biomart.halved.filtered.tsv
	awk -F"\t" '{print $$9}' $< | sort | uniq > $@
	
commAncestors_list.labeled.tsv: comm_ancestors.tsv
	#Manual labelling with an ordinal number using https://www.ncbi.nlm.nih.gov/Taxonomy
	
barplot_ssdOnly.tsv: ssd_paralogs.tsv
	awk -F"\t" '{print $$9}' $< | sort | uniq -c | awk '{print $$1 "\t" $$2}' > $@
	
barplot_wgdOnly.tsv: ohnologs_makino_parampriya_merged.filtered.tsv
	awk -F"\t" '{print $$9}' $< | sort | uniq -c | awk '{print $$1 "\t" $$2}' > $@
	
barplot_all.tsv: human_paralogs_biomart.halved.filtered.tsv
	awk -F"\t" '{print $$9}' $< | sort | uniq -c | awk '{print $$1 "\t" $$2}' > $@



gencode.v41.annotation.gtf.gz:
	wget -O $@ 'https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/gencode.v41.annotation.gtf.gz'
	
gencode.gtf.gz: gencode.v41.annotation.gtf.gz
	mv $< $@

gencode.gtf: gencode.gtf.gz
	gzip -d $<
	# NR = 3,375,764

gencode.geneOnly.gtf: gencode.gtf
	awk -F"\t" '$$3=="gene"' $< > $@
	# NR = 61,852
	
gencode.geneOnly.protcod.gtf: gencode.geneOnly.gtf
	awk -F"\t" '$$9~/gene_type "protein_coding"/' $< > $@
	# NR = 20,017
	
gencode.geneOnly.miRNA.gtf: gencode.geneOnly.gtf
	awk -F"\t" '$$9~/gene_type "miRNA"/' $< > $@
	# NR = 1,879
		
gencode.geneOnly.miRNA_intWithProtcod.bed: gencode.geneOnly.miRNA.bed gencode.geneOnly.protcod.bed
	bedtools intersect -a $< -b $(word 2, $^) > $@
	# NR = 1,278
	
ohnologsCouples.tsv: ohnologs_makino_parampriya_merged.filtered.tsv
	ln -s ./$< ./$@
	# NR = 1,673
		
ohnologsSingles.tsv: ohnologsCouples.tsv
	awk -F"\t" '{print $$1 ; print $$2}' $< | sort | uniq > $@
	# NR = 2,228	

%.bed: %.gtf
	awk -F"\t" '{split($$9,a," "); print $$1 "\t" $$4 "\t" $$5 "\t" substr(a[2], 2, 15) "\t" $$6 "\t" $$7 "\t" substr($$9, length(a[2])+10, length($$9))}' $< > $@
	# GTF to BED general conversion rule

ohnologsSingles.bed: ohnologsSingles.tsv gencode.geneOnly.bed
	filter_1col 4 $< < $(word 2, $^) > $@
	# NR = 2,230
	
protodictionary.tsv: gencode.geneOnly.miRNA_intWithProtcod.bed ohnologsSingles.bed
	bedtools intersect -wb -a $< -b $(word 2, $^) > $@
	# NR = 219
	
dictionary.tsv: protodictionary.tsv
	awk -F"\t" '{print $$11 "\t" $$4 "\t" $$7}' $< | tr -d '";' > $@
	# NR = 219

ohnologs_miRNA_couples.tsv: ohnologsCouples.tsv
	translate -a -d -v -e NA dictionary.tsv 1 2 < $< | grep -vw NA > $@
	# NR = 



