.DELETE_ON_ERROR:

#starting file: extended.paralogs_miRNAdated.mirgeneFlagged_couples.tsv comes from v7_mirGeneDBFilter

################################	gtf2bed converter using gff2tab (super OP tool from ircc)	###################################
%.bed: %.gtf
	cat $< | gff2tab gene_type gene_id gene_name | awk '{print $$1 "\t" $$4 "\t" $$5 "\t" substr($$10, 1, 15) "\t" $$6 "\t" $$7 "\t" $$9 "\t" $$11}' > $@
###############################################################################################################################

ohnomirnaBC_ensg_hg.tsv: extended.paralogs_miRNAdated.mirgeneFlagged_couples.tsv
	awk -F"\t" '$$17=="WGD" && $$6=="mirgene_conf" && $$14=="mirgene_conf" {print $$5 "\t" $$7 "\t" $$1 "\n" $$13 "\t" $$15 "\t" $$9 }' $< \
	| sort | uniq > $@
	#BC stands for "Both Confirmed" from MiRGeneDB database
	#NR = 28

paralogmirnaBC_ensg_hg.tsv: extended.paralogs_miRNAdated.mirgeneFlagged_couples.tsv
	awk -F"\t" '$$17=="SSD" && $$6=="mirgene_conf" && $$14=="mirgene_conf" {print $$5 "\t" $$7 "\t" $$1 "\n" $$13 "\t" $$15 "\t" $$9 }' $< \
	| sort | uniq > $@
	#BC stands for "Both Confirmed" from MiRGeneDB database
	#NR = 45

%_filter.tsv: %BC_ensg_hg.tsv
	awk -F"\t" '{print $$1}' $< > $@

TarBase_v8_download.txt:
	#Request and download the database from: https://dianalab.e-ce.uth.gr/html/diana/web/index.php?r=tarbasev8/index and extract it
	#NR = 927,120

TarBase_v8.hsa.tsv: TarBase_v8_download.txt
	awk -F"\t" '$$4=="Homo sapiens" || $$4=="species"' $< > $@
	#NR = 420,710		(1 row is the header)	(check the number because it reduced

TarBase_v8.hsa.normDir.tsv: TarBase_v8.hsa.tsv
	awk -F"\t" '$$7!="Cancer/Malignant" && $$9=="POSITIVE" && $$10=="DIRECT" {print $$0}' $< > $@

hsa.gff3:
	wget -O $@ 'https://www.mirbase.org/ftp/CURRENT/genomes/hsa.gff3'

mirna.prim_transcripts.gff3: hsa.gff3
	awk -F"\t" '$$3=="miRNA_primary_transcript" {print $$0}' $< > $@

mirna.prim_transcripts.tsv: mirna.prim_transcripts.gff3
	cat $< | perl -lane 'BEGIN{$$,="\t"} @spl=split(";",$$F[8]); $$spl[0]=~s/^ID=(.*)/$$1/; $$spl[1]=~s/^Alias=(.*)/$$1/; $$spl[2]=~s/^Name=(.*)/$$1/; {print @spl}' > $@

mirna.mature.gff3: hsa.gff3
	awk -F"\t" '$$3=="miRNA" {print $$0}' $< > $@

mirna.mature.tsv: mirna.mature.gff3
	cat $< | perl -lane 'BEGIN{$$,="\t"} @spl=split(";",$$F[8]); $$spl[0]=~s/^ID=(.*)/$$1/; $$spl[1]=~s/^Alias=(.*)/$$1/; $$spl[2]=~s/^Name=(.*)/$$1/; $$spl[3]=~s/^Derives_from=(.*)/$$1/; {print @spl}' > $@
